# Generated by Django 5.2.4 on 2025-07-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelydropusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedelivery',
            name='current_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
