# Generated by Django 5.2.4 on 2025-07-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelydropusers', '0002_packagedelivery_current_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getaquote',
            name='package_type',
        ),
        migrations.RemoveField(
            model_name='getaquote',
            name='package_weight',
        ),
        migrations.AddField(
            model_name='getaquote',
            name='carton_dimension',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
